--------------------------------------------------------
--  DDL for Table STAFFCOMMUTINGMANAGEMENT
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" 
   (	"INDEXNUM" VARCHAR2(200 BYTE), 
	"TIMETABLECODE" VARCHAR2(200 BYTE), 
	"WORKDATE" DATE, 
	"WORKDATE_STR" NVARCHAR2(100), 
	"WORKCHK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAFFCOMMUTINGMANAGEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT_PK" ON "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" ("INDEXNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STAFFCOMMUTINGMANAGEMENT
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" ADD CONSTRAINT "STAFFCOMMUTINGMANAGEMENT_PK" PRIMARY KEY ("INDEXNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" MODIFY ("WORKCHK" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" MODIFY ("WORKDATE_STR" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" MODIFY ("WORKDATE" NOT NULL ENABLE);
  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" MODIFY ("INDEXNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STAFFCOMMUTINGMANAGEMENT
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."STAFFCOMMUTINGMANAGEMENT" ADD CONSTRAINT "SCM_TCODE_FK" FOREIGN KEY ("TIMETABLECODE")
	  REFERENCES "STARBUCKS"."WORKTIMETABLE" ("TIMETABLECODE") ON DELETE CASCADE ENABLE;


create sequence StaffCommutingManagement_seq
    start with 30
    increment by 1
    nomaxvalue
    nominvalue
    nocycle
    nocache
;