--------------------------------------------------------
--  DDL for Table MemberAdmin [직원]
--------------------------------------------------------
-- type         > 2:직원(알바), 3:매장별매니저, 4:관리자 (직급 구분)
-- storeNum     > [매장] 매장코드, 매장이름 가져올 때
-- managerId    > [회원] 테이블에 존재하는 ID인지 확인하여 ajax로 확인필요 (FK 참조 안함, 선 select)

create table memberAdmin (
    adminNum number constraint admin_an_pk primary key,
    type number(1) constraint admin_type_check CHECK (type in (2,3,4)) NOT NULL,
    storeCode number constraint admin_sn_fk references store(storeCode) ON DELETE CASCADE,
    managerId varchar2(200),
    "TIMETABLE" VARCHAR2(100 BYTE) DEFAULT 'N'
);

-- seq
create SEQUENCE admin_seq
    increment by 1
    start with 45
    nomaxvalue
    nominvalue
    nocycle
    nocache
;

SET DEFINE OFF

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (1, 4, 1716, 'admin');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (2, 3, 1716, 'manager1716');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (3, 2, 1716, 'employee171601');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (4, 2, 1716, 'employee171602');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (5, 3, 1710, 'manager1710');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (6, 2, 1710, 'employee171001');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (7, 2, 1710, 'employee171002');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (8, 3, 433, 'manager433');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (9, 2, 433, 'employee43301');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (10, 2, 433, 'employee43302');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (11, 3, 430, 'manager430');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (12, 2, 430, 'employee43001');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (13, 2, 430, 'employee43002');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (14, 3, 565, 'manager565');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (15, 2, 565, 'employee56501');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (16, 2, 565, 'employee56502');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (17, 3, 325, 'manager325');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (18, 2, 325, 'employee32501');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (19, 2, 325, 'employee32502');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (20, 3, 316, 'manager316');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (21, 2, 316, 'employee31601');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (22, 2, 316, 'employee31602');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (23, 3, 338, 'manager338');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (24, 2, 338, 'employee33801');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (25, 2, 338, 'employee33802');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (26, 3, 300, 'manager300');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (27, 2, 300, 'employee30001');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (28, 2, 300, 'employee30002');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (29, 3, 497, 'manager497');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (30, 2, 497, 'employee49701');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (31, 2, 497, 'employee49702');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (32, 3, 321, 'manager321');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (33, 2, 321, 'employee32101');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (34, 2, 321, 'employee32102');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (35, 3, 306, 'manager306');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (36, 2, 306, 'employee30601');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (37, 2, 306, 'employee30602');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (38, 3, 394, 'manager394');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (39, 2, 394, 'employee39401');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (40, 2, 394, 'employee39402');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (41, 3, 407, 'manager407');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (42, 2, 407, 'employee40701');

INSERT INTO MEMBERADMIN (ADMINNUM, TYPE, STORECODE, MANAGERID) 
VALUES (43, 2, 407, 'employee40702');



commit;

