--------------------------------------------------------
--  DDL for Table STARHISTORY
--------------------------------------------------------

  CREATE TABLE "STARBUCKS"."STARHISTORY" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(200 BYTE), 
	"CARDNUM" NUMBER, 
	"USESTAR" NUMBER DEFAULT 0, 
	"OUTSTAR" NUMBER DEFAULT 0, 
	"TOTALSTAR" NUMBER DEFAULT 0, 
	"STATE" VARCHAR2(20 BYTE), 
	"STORENAME" VARCHAR2(200 BYTE), 
	"TOTALPRICE" NUMBER, 
	"SAVEDATE" DATE, 
	"VALIDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SH_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARBUCKS"."SH_NUM_PK" ON "STARBUCKS"."STARHISTORY" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STARHISTORY
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."STARHISTORY" ADD CONSTRAINT "SH_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STARHISTORY
--------------------------------------------------------

  ALTER TABLE "STARBUCKS"."STARHISTORY" ADD CONSTRAINT "M_ID_FK" FOREIGN KEY ("ID")
	  REFERENCES "STARBUCKS"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;

-------------------seq
create sequence star_seq increment by 1 start with 1 maxvalue 99999999999999999 minvalue 1 NOCACHE  NOORDER  NOCYCLE;
---------------------insert
REM INSERTING into STARBUCKS.STARHISTORY
SET DEFINE OFF;
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (13,'jy1234',29192274,6,0,6,'적립','홍대갤러리',75000,to_date('20/11/29','RR/MM/DD'),to_date('21/11/29','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (15,'jy555',1088008,8,0,8,'적립','구로에이스',67400,to_date('20/11/29','RR/MM/DD'),to_date('21/11/29','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (8,'customer06',124453545756,3,1,22,'적립','신촌',12000,to_date('20/11/22','RR/MM/DD'),to_date('20/11/22','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (9,'customer02',27442177,4,0,56,'적립','홍대',7000,to_date('20/11/22','RR/MM/DD'),to_date('20/11/22','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (10,'customer05',11111122222,1,0,10,'적립','신촌',10000,to_date('20/11/28','RR/MM/DD'),to_date('21/11/28','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (11,'customer01',353253246,6,0,40,'적립','강남',17000,to_date('20/11/26','RR/MM/DD'),to_date('21/11/28','RR/MM/DD'));
Insert into STARBUCKS.STARHISTORY (NUM,ID,CARDNUM,USESTAR,OUTSTAR,TOTALSTAR,STATE,STORENAME,TOTALPRICE,SAVEDATE,VALIDDATE) values (16,'jinny33',null,2,0,2,'적립','사당역',39000,to_date('20/11/29','RR/MM/DD'),to_date('21/11/29','RR/MM/DD'));
